import type { Metadata } from "next";
import "./globals.css";
import { roboto, righteous } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${roboto.variable} ${righteous.variable} dark:bg-gray-950 font-roboto`}
      >
        {children}
      </body>
    </html>
  );
}
