import type { Metadata } from "next";
import "./globals.css";
import { roboto, righteous, cairo } from "@/lib/fonts";
import App from "./App";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { locales } from "@/i18n/routing";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: {
    default: "Educational",
    template: "%s | Educational",
  },
  description: "Generated by Educational",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const isArabic = locale === "ar";
  if (!hasLocale(locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale} dir={isArabic ? "rtl" : "ltr"} className="dark">
      <body
        className={`${roboto.variable} ${righteous.variable} ${cairo.variable}
          ${isArabic ? "font-cairo" : "font-roboto"}`}
      >
        <NextIntlClientProvider>
          <App>{children}</App>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
